# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - Ram-USB-HID
    paths: 'SSS2_Firmware/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    env: 
      ARDUINO_IDE_VERSION: "1.8.13"
      DEVICE: "teensy36"
      SPEED: "180"
      USBTYPE: rawhid 
    steps:
        - name: Check out repository 
          uses: actions/checkout@v1

        - name: Install-Arduino
          run: |
              wget --quiet https://downloads.arduino.cc/arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz
              mkdir $HOME/arduino_ide
              tar xf arduino-$ARDUINO_IDE_VERSION-linux64.tar.xz -C $HOME/arduino_ide/
        - name: Install-Tennsyduino
          run: |  
                curl -fsSL https://www.pjrc.com/teensy/td_153/TeensyduinoInstall.linux64 -o TeensyduinoInstall.linux64
                chmod +x TeensyduinoInstall.linux64
                /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
                sleep 3
                export DISPLAY=:1.0
                ./TeensyduinoInstall.linux64 --dir=$HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION
        - name: Check-present-working-Directory 
          run: |
                pwd
                ls -r
                cd ..
                ls
        - name: Install Additional Libraries
          run: |
                cd $HOME/arduino_ide/arduino-$ARDUINO_IDE_VERSION/
                ./arduino --install-library "base64" 
                ./arduino --install-library "OneButton"
        - name: Verify-Code 
          run: |
            cd SSS2_Firmware
            wget  https://raw.githubusercontent.com/gannaramu/Teensy-Github-Action/master/check-status.py
            wget  https://raw.githubusercontent.com/gannaramu/Teensy-Github-Action/master/build-sketches.sh
            bash build-sketches.sh
        - name: Chekcing Files
          run: ls    
        
        - name: upload-Code 
          uses: actions/upload-artifact@v2
          with:
            name: my-artifact
            path: SSS2_Firmware/Final.txt
        - id: status
          run: cat SSS2_Firmware/Final.txt | grep SSS2_Firmware.ino:✓ || exit 120
         
#echo "##[set-output name=data;]$(
#        - name: Time badge
#           uses: RubbaBoy/BYOB@v1.1.0
#           with:
#              NAME: time
#              LABEL: 'SSS2_Firnware.ino'
#              STATUS: ${{ steps.status.outputs.data }}
#              COLOR: 43B00D
#              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
